### ISSUE TITLE
Inference speed mechanism or Model size compression ?

### ISSUE THREAD

**Issue by sravanthOppo27** [Xiuyu-Li/q-diffusion#1]

**Comment by Xiuyu-Li** [comment]
Hi, at the moment, only simulated quantization is implemented in this repository for FID evaluation. We will be releasing a significantly updated arXiv paper that includes comprehensive data on model sizes.

**Comment by continue-revolution** [comment]
Do you plan to build an end-to-end quantization for stable diffusion? If yes, I want to know the approximate time.

**Comment by Xiuyu-Li** [comment]
@continue-revolution Hi Chengsong,

End-to-end quantization is on our roadmap, and we're aiming to work on it in the coming months. Please stay tuned for updates, and thanks for your interest in the project! We also welcome contributions from the open-source community to help expedite this process.

**Comment by continue-revolution** [comment]
@Xiuyu-Li Glad to contribute in some way. Have sent an email to your berkeley address.

**Comment by Jack47** [comment]
can't wait to see "a significantly updated arXiv paper that includes comprehensive data on model sizes". cheers~

**Comment by sravanthOppo27** [comment]
When can we expect the code for Calibration ?

**Comment by lucasjinreal** [comment]
Any date we expected the speedup with quantization?
