### ISSUE TITLE
load cifar_w8a8_ckpt.pth

### ISSUE THREAD

**Issue by foreverlove944** [Xiuyu-Li/q-diffusion#11]
When executing this line of code: `resume_cali_model(qnn, args.cali_ckpt, cali_data, args.quant_act, "qdiff", cond=False)`, the model cannot be loaded properly when running `qnn.load_state_dict(ckpt, strict=(act_quant_mode=='qdiff'))`. Can you tell me how to solve this problem? Thank you.
<img width="749" alt="2023-07-11 104114" src="https://github.com/Xiuyu-Li/q-diffusion/assets/79123282/36ae6754-1198-4e26-a92e-37804c056a0b">
<img width="749" alt="2023-07-11 104114" src="https://github.com/Xiuyu-Li/q-diffusion/assets/79123282/47ab8909-2eed-4474-9406-4dbca4f3bbe4">

**Comment by Xiuyu-Li** [comment]
Hi, this seems to be a size mismatch problem due to not enabling [shortcut splitting](https://github.com/Xiuyu-Li/q-diffusion/blob/94fd0ecabc6e7545208c4809d84df091999ce4ad/scripts/sample_diffusion_ddim.py#L68) in the ddim model based on your error message. Can you set `split_shortcut=True` when initializing the model and see if that fixes the issue?

**Comment by foreverlove944** [comment]
Thank you for the suggestion, but it did not solve the problem.The command I entered is as shown in the screenshot.
<img width="881" alt="2023-07-11 143001" src="https://github.com/Xiuyu-Li/q-diffusion/assets/79123282/fbc4ddf8-009f-4a55-b5a3-de39ca967c67">
<img width="580" alt="2023-07-11 143133" src="https://github.com/Xiuyu-Li/q-diffusion/assets/79123282/b34b31af-f40c-459d-879e-e27d22cd7c45">

**Comment by Xiuyu-Li** [comment]
It seems like the splitting was not done as expected somehow. I just tested with `python scripts/sample_diffusion_ddim.py --config configs/cifar10.yml --use_pretrained --timesteps 100 --eta 0 --skip_type quad --ptq --weight_bit 8 --quant_mode qdiff --quant_act --act_bit 8 --a_sym --split -l cifar_out --cali_ckpt cifar_w8a8_ckpt.pth` using the latest codebase and it works fine. 

I am not sure what's going on in your case, but my guess is there might be some discrepancies with the dependencies (or codes if you have changed some) that made splitting not get called properly. Could you try doing `pip install q-diffusion` and running the previous command using again? Also please try doing this with an unmodified codebase if you have done some modifications and it doesn't work in your current one.

**Comment by foreverlove944** [comment]
Thank you for your help. I have resolved the issue after downloading the code again.
