### ISSUE TITLE
Does q-diffusion work on SDXL?

### ISSUE THREAD

**Issue by TruthSearcher** [Xiuyu-Li/q-diffusion#22]

**Comment by lucasjinreal** [comment]
Also want to know, how's the performance effected?

**Comment by Xiuyu-Li** [comment]
The newest updates of TensorRT featured Q-Diffusion and added support to quantize SDXL. Check out their official [example](https://github.com/NVIDIA/TensorRT/tree/release/9.3/demo/Diffusion#faster-text-to-image-using-sdxl--int8-quantization-using-ammo).

**Comment by ApolloRay** [comment]
> The newest updates of TensorRT featured Q-Diffusion and added support to quantize SDXL. Check out their official [example](https://github.com/NVIDIA/TensorRT/tree/release/9.3/demo/Diffusion#faster-text-to-image-using-sdxl--int8-quantization-using-ammo).

It doesn't work, and it need A100.
