### ISSUE TITLE
What is the main comparison of the paper

### ISSUE THREAD

**Issue by sravanthOppo27** [Xiuyu-Li/q-diffusion#4]
Dear Author , In the paper you are mainly comparing the quantized model which was calibrated by taking data at multiple time steps vs the quantized model which was calibrated by a random time step output .

Correct me if I am wrong

**Comment by Xiuyu-Li** [comment]
Our method calibrates the quantized model using data from multiple time steps, while the PTQ baselines do not involve a calibration process. We are going to have a more detailed discussion on the effects of calibration data selection in the next arxiv update.
