### ISSUE TITLE
Loading quantized model checkpoint error

### ISSUE THREAD

**Issue by arthursunbao** [Xiuyu-Li/q-diffusion#8]
Hi,
I am trying to reproduce the results in the paper for stable diffusion. and use the sdv1.4 ckpt and sd_w4a8_ckpt.pth for ptq using NVIDIA V100

My command is like the following:
python scripts/txt2img.py --prompt "a puppet wearing a hat"  --outdir /data --H 512 --W 512 --n_samples 1 --scale 11 --seed 100  --verbose --cond   --ddim_steps 28 --n_iter 1 --ptq --weight_bit 8 --quant_mode qdiff  --cali_ckpt /data/q-diffusion-master/sd_w4a8_ckpt.pth

And I have the following error: 

Traceback (most recent call last):
  File "scripts/txt2img.py", line 451, in <module>
    main()
  File "scripts/txt2img.py", line 345, in main
    resume_cali_model(qnn, opt.cali_ckpt, cali_data, opt.quant_act, "qdiff", cond=opt.cond)
  File "/data/q-diffusion-master/qdiff/utils.py", line 67, in resume_cali_model
    qnn.load_state_dict(ckpt, strict=False)
  File "/data/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1672, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for QuantModel:
        size mismatch for model.output_blocks.0.0.skip_connection.weight_quantizer.alpha: copying a param with shape torch.Size([1280, 1280, 1, 1]) from checkpoint, the shape in current model is torch.Size([1280, 2560, 1, 1]).
        size mismatch for model.output_blocks.1.0.skip_connection.weight_quantizer.alpha: copying a param with shape torch.Size([1280, 1280, 1, 1]) from checkpoint, the shape in current model is torch.Size([1280, 2560, 1, 1]).
        size mismatch for model.output_blocks.2.0.skip_connection.weight_quantizer.alpha: copying a param with shape torch.Size([1280, 1280, 1, 1]) from checkpoint, the shape in current model is torch.Size([1280, 2560, 1, 1]).
        size mismatch for model.output_blocks.3.0.skip_connection.weight_quantizer.alpha: copying a param with shape torch.Size([1280, 1280, 1, 1]) from checkpoint, the shape in current model is torch.Size([1280, 2560, 1, 1]).
        size mismatch for model.output_blocks.4.0.skip_connection.weight_quantizer.alpha: copying a param with shape torch.Size([1280, 1280, 1, 1]) from checkpoint, the shape in current model is torch.Size([1280, 2560, 1, 1]).
        size mismatch for model.output_blocks.5.0.skip_connection.weight_quantizer.alpha: copying a param with shape torch.Size([1280, 1280, 1, 1]) from checkpoint, the shape in current model is torch.Size([1280, 1920, 1, 1]).
        size mismatch for model.output_blocks.6.0.skip_connection.weight_quantizer.alpha: copying a param with shape torch.Size([640, 1280, 1, 1]) from checkpoint, the shape in current model is torch.Size([640, 1920, 1, 1]).
        size mismatch for model.output_blocks.7.0.skip_connection.weight_quantizer.alpha: copying a param with shape torch.Size([640, 640, 1, 1]) from checkpoint, the shape in current model is torch.Size([640, 1280, 1, 1]).
        size mismatch for model.output_blocks.8.0.skip_connection.weight_quantizer.alpha: copying a param with shape torch.Size([640, 640, 1, 1]) from checkpoint, the shape in current model is torch.Size([640, 960, 1, 1]).
        size mismatch for model.output_blocks.9.0.skip_connection.weight_quantizer.alpha: copying a param with shape torch.Size([320, 640, 1, 1]) from checkpoint, the shape in current model is torch.Size([320, 960, 1, 1]).
        size mismatch for model.output_blocks.10.0.skip_connection.weight_quantizer.alpha: copying a param with shape torch.Size([320, 320, 1, 1]) from checkpoint, the shape in current model is torch.Size([320, 640, 1, 1]).
        size mismatch for model.output_blocks.11.0.skip_connection.weight_quantizer.alpha: copying a param with shape torch.Size([320, 320, 1, 1]) from checkpoint, the shape in current model is torch.Size([320, 640, 1, 1]).

It seems that sd_w4a8_ckpt.pth weight shape is not the same for QuantModel shape. 
I use qnn.load_state_dict(ckpt, strict=False) and still have the same problem.

Can you please help to take a look?

Jason

**Comment by Xiuyu-Li** [comment]
Hi, it seems like you did not enable shortcut splitting in your script, while our provided checkpoint applies it by default (see section 3.3.2 of our paper for details). Also, the current checkpoint is for INT4 weights. Can you try running the command below to see if you can successfully load the model?
```bash
python scripts/txt2img.py --prompt "a puppet wearing a hat" --plms --cond --ptq --weight_bit 4 --quant_mode qdiff --no_grad_ckpt --split --n_samples 5 --outdir /data --cali_ckpt /data/q-diffusion-master/sd_w4a8_ckpt.pth
``` 
For more details on the provided checkpoints, please take a closer look at the arguments in [README](https://github.com/Xiuyu-Li/q-diffusion#usage). I will get the INT8 checkpoints uploaded soon.
